mysite/Chat_DJ4E/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('', include('publicchat.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('friends/', include('friends.urls')),
    path('privatechat/', include('privatechat.urls')),
    path('notifications/', include('notifications.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('accounts/reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# urlpatterns += [
#     re_path(r'^site/(?P<path>.*)$', serve,
#         {'document_root': os.path.join(BASE_DIR, 'site'),
#          'show_indexes': True},
#         name='site_path'
#         ),
# ]

# Serve the favicon
# urlpatterns += [
#     path('favicon.ico', serve, {
#             'path': 'favicon.ico',
#             'document_root': os.path.join(BASE_DIR, 'home/static'),
#         }
#     ),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_login = 'registration/login_social.html'
urlpatterns.insert(0,
                    path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                    )

mysite/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('<int:pk>/', views.ProfileView.as_view(), name="profile"),
    path('<int:pk>/edit/', views.EditProfileView.as_view(), name="edit"),
    path('search/', views.AccountSearch.as_view(), name="search"),
    path('<int:pk>/edit/crop_image/', views.crop_image, name="crop_image"),
    path('store_timezone_offset/', views.store_timezone_offset, name="store_timezone_offset"),
]

mysite/chat/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='chat'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),

]

mysite/friends/urls.py
from django.urls import path
from . import views

app_name='friends'
urlpatterns = [
    path('friend_request/', views.send_friend_request, name="friend_request"),
    path('<int:pk>/friends_requests/', views.FriendRequestsView.as_view(), name="friend_requests"),
    path('<int:pk>/friend_list/', views.FriendListView.as_view(), name="friend_list"),
    path('friend_request_accept/', views.accept_friend_request, name="accept_friend_request"),
    path('friend_request_decline/', views.decline_friend_request, name="decline_friend_request"),
    path('friend_request_cancel/', views.cancel_friend_request, name="cancel_friend_request"),
    path('friend_remove/', views.unfriend, name="remove_friend"),
]

mysite/privatechat/urls.py
from django.urls import path
from . import views

app_name='privatechat'
urlpatterns = [
    path('<int:user_id>/all_chats/', views.PrivateChatAllChatsView.as_view(), name='all'),
    path('<int:room_id>/chat/', views.PrivateChatView.as_view(), name='chat'),
    path('update_chat_log/', views.update_chat_log, name='update_chat_log'),
    path('create_chat/', views.create_chat, name='create_chat'),
    path('get_previous_messages_private/', views.get_previous_messages_private, name='get_previous_messages_private'),
    path('update_chatroom_unread_messages/', views.update_chatroom_unread_messages, name="update_chatroom_unread_messages"),
]

mysite/friends/models.py
from django.db import models
from django.conf import settings


class FriendList(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="owner")
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="friends")

    def __str__(self):
        return self.owner.username

    def add_friend(self, account):
        if not account in self.friends.all():
            self.friends.add(account)

    def remove_friend(self, account):
        # remove friend from your friends list and remove yourself from their friends list
        if account in self.friends.all():
            self.friends.remove(account)
        account_friend_list = FriendList.objects.get(owner=account)
        if self.owner in account_friend_list.friends.all():
            account_friend_list.friends.remove(self.owner)

    def is_mutual_friend(self, account):
        if account in self.friends.all():
            return True
        return False


class FriendRequest(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver")
    is_active_request = models.BooleanField(blank=True, null=False, default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('sender', 'receiver',)

    def __str__(self):
        return self.sender.username

    def accepted(self):
        sender_friend_list = FriendList.objects.get(owner=self.sender)
        receiver_friend_list = FriendList.objects.get(owner=self.receiver)
        if sender_friend_list and receiver_friend_list:
            sender_friend_list.add_friend(self.receiver)
            receiver_friend_list.add_friend(self.sender)
        else:
            raise Exception("unable to accept friend request")
        self.is_active_request = False
        self.save()

    def declined(self):
        # friend request declined by receiver
        # will remove the request from the senders list of sent requests but notification won't be sent
        self.is_active_request = False
        self.save()

    def cancelled(self):
        # friend request cancelled by sender
        # will remove the notification on the receivers end
        self.is_active_request = False
        self.save()

mysite/friends/views.py
import json
import logging
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.core.exceptions import PermissionDenied

from account.models import Account
from friends.models import FriendRequest, FriendList
from notifications.models import FriendNotifications
from privatechat.models import PrivateChat

logger = logging.getLogger('django')


class FriendListView(View):
    template_name = "friends/friend_list.html"

    def get(self, request, pk):
        user = request.user
        if request.user.is_authenticated:
            account = get_object_or_404(Account, id=pk)

            # if no friend list exists for account - create one so that their friend list page can still be accessed
            try:
                friend_list_obj = FriendList.objects.get(owner=account)
            except FriendList.DoesNotExist:
                friend_list_obj = FriendList(owner=account)

            friend_list = []
            for friend in friend_list_obj.friends.all():
                friend_list.append(friend)

            ctx = {'friend_list': friend_list, 'account': account, 'user': user}
            return render(request, self.template_name, ctx)
        else:
            return redirect("login")
            

class FriendRequestsView(View):
    template_name = "friends/friend_requests.html"

    def get(self, request, pk):
        user = request.user
        if request.user.is_authenticated:
            account = get_object_or_404(Account, id=pk)
            if account != user:
                raise PermissionDenied
            else:
                friend_requests = FriendRequest.objects.filter(receiver=account, is_active_request=True)
                ctx = {'friend_requests': friend_requests}
                return render(request, self.template_name, ctx)
        else:
            return redirect("login")


def is_friend_request_active(sender, receiver):
    try:
        return FriendRequest.objects.get(sender=sender, receiver=receiver, is_active_request=True)
    except FriendRequest.DoesNotExist as e:
        return False


def send_friend_request(request, *args, **kwargs):
    # using ajax request so that page isn't refreshed if friend request cannot be sent for some reason
    user = request.user
    payload = {}
    if request.method == "POST" and user.is_authenticated:
        user_id = request.POST.get("receiver_user_id")

        # if friend_list for user sending request doesn't currently exist, create one
        try:
            friend_list = FriendList.objects.get(owner=user)
        except FriendList.DoesNotExist:
            friend_list = FriendList(owner=user)

        if user_id:
            receiver = Account.objects.get(pk=user_id)
            try:
                friend_request = FriendRequest.objects.get(sender=user, receiver=receiver)
                # logic to cover any faults elsewhere where user is somehow able to attempt to send a second
                # friend request to account despite one already being active
                if friend_request.is_active_request:
                    raise Exception("There is already an active pending friend request for this account")
                friend_request.is_active_request = True
                friend_request.save()
                payload['response'] = 'success'
            except FriendRequest.DoesNotExist:
                friend_request = FriendRequest(sender=user, receiver=receiver)
                friend_request.save()
                payload['response'] = 'success'
            if payload['response'] == None:
                payload['response'] = 'Unexpected error occurred'
        else:
            payload['response'] = 'Unable to send friend request'
    else:
        return redirect("login")
    return HttpResponse(json.dumps(payload), content_type="application/json")
                

def accept_friend_request(request, *args, **kwargs):
    # a lot of the error handling below is in case logic elsewhere in site is broken
    user = request.user
    payload = {}
    if request.method == "POST" and user.is_authenticated:
        received_friend_request_id = request.POST.get("received_friend_request_id")
        if received_friend_request_id:
            try:
                received_friend_request = FriendRequest.objects.get(pk=received_friend_request_id)
                try:
                    friend_notification = FriendNotifications.objects.get(friend_request_id=received_friend_request_id)
                    friend_notification.engaged = True
                    friend_notification.save()
                except Exception as e:
                    logging.warning(f'user {user.id} - accept_friend_request view - no friend notification found - {str(e)}')
                if received_friend_request.receiver == user:
                    # handle if sender has cancelled friend request
                    if received_friend_request.is_active_request == False:
                        payload['response'] = "friend request is no longer active"
                    else:
                        try:
                            received_friend_request.accepted()
                        except Exception as e:
                            payload['response'] = "unable to accept request"
                        else:
                            payload['response'] = "success"
                else:
                    payload['response'] = "error - not your friend request to accept"
            except Exception as e:
                payload['response'] = f"unexpected error occurred: {str(e)}"
        else:
            payload['response'] = "request id not found"
    else:
        return redirect("login")
    return HttpResponse(json.dumps(payload), content_type="application/json")


def decline_friend_request(request, *args, **kwargs):
    user = request.user
    payload = {}
    if request.method == "POST" and user.is_authenticated:
        received_friend_request_id = request.POST.get("received_friend_request_id")
        if received_friend_request_id:
            try:
                received_friend_request = FriendRequest.objects.get(pk=received_friend_request_id)
                try:
                    friend_notification = FriendNotifications.objects.get(friend_request_id=received_friend_request_id)
                    friend_notification.engaged = True
                    friend_notification.save()
                except Exception as e:
                    logging.warning(f'user {user.id} - decline_friend_request view - no friend notification found - {str(e)}')
                if received_friend_request.receiver == user:
                    if received_friend_request.is_active_request == False:
                        payload['response'] = "friend request is no longer active"
                    else:
                        try:
                            received_friend_request.declined()
                        except Exception as e:
                            payload['response'] = f"unable to decline request: {str(e)}"
                        else:
                            payload['response'] = "success"
                else:
                    payload['response'] = "error - not your friend request to decline"
            except Exception as e:
                payload['response'] = f"unexpected error occurred: {str(e)}"
        else:
            payload['response'] = "request id not found"
    else:
        return redirect("login")
    return HttpResponse(json.dumps(payload), content_type="application/json")


def cancel_friend_request(request, *args, **kwargs):
    user = request.user
    payload = {}
    if request.method == "POST" and user.is_authenticated:
        user_id = request.POST.get("receiver_user_id")
        sent_friend_request_id = request.POST.get("friend_request_id")
        if user_id:
            receiver = Account.objects.get(pk=user_id)
            try:
                friend_request = FriendRequest.objects.filter(sender=user, receiver=receiver, is_active_request=True)
            except:
                payload['response'] = "friend request doesn't exist"

            try:
                friend_notification = FriendNotifications.objects.get(friend_request_id=sent_friend_request_id)
                friend_notification.engaged = True
                friend_notification.save()
            except Exception as e:
                logging.warning(f'user {user.id} - cancel_friend_request view - no friend notification found - {str(e)}')
            
            # should only be one request as combination of sender and user is unique, but handle and log just in case
            if len(friend_request) > 1:
                logging.warning(f'cancel_friend_request view - more than one friend request found from user {user.id} to receiver {receiver.id}')
            for req in friend_request:
                req.cancelled()
            payload['response'] = "success"
        else:
            payload['response'] = "user id not provided"
    else:
        return redirect("login")
    return HttpResponse(json.dumps(payload), content_type="application/json")   


def unfriend(request, *args, **kwargs):
    user = request.user
    payload = {}
    if request.method == "POST" and user.is_authenticated:
        user_id = request.POST.get("receiver_user_id")
        if user_id:
            try:
                account = Account.objects.get(pk=user_id)
                friend_list = FriendList.objects.get(owner=user)
                friend_list.remove_friend(account)
                payload['response'] = "success"
                try:
                    users = sorted(list((account.email, user.email)))
                    title = " ".join(users) + " private chat"
                    privatechat = PrivateChat.objects.get(title=title)
                    privatechat.delete()
                except PrivateChat.DoesNotExist:

mysite/friends/templates/friends/friend_list.html
{% extends 'base_menu.html' %}
{% load static %}
{% block content %}

<style type="text/css">

    .card{
        background-color: #303333;
    }

    #id_account_card{
        background-color: #4b4b4d;
        width: 100%;
    }

    .profile-img{
        max-height: 100px;
        max-width: 100px;
    }

    .send-friend-message-container{
        margin-left: auto;
    }

    #id_account_row{
        width: 100%;
    }

    .card-right{
        width: 100%;
    }

    .account-profile-link {
        text-decoration: none !important;
    }

    .account-username {
        color: white;
        font-size: 20pt;
    }

    .message-button {
        background-color: #6d6f73;
        cursor: pointer;
        transition: background-color 0.2s ease-in-out;
        font-weight: bold;
        color: white;
    }

    .message-button:hover {
        background-color: #9779a8;
        color: white;
    }

    @media (max-width: 649px) {
        .card-image {
            margin: 5px !important;
            max-height: 75px;
            max-width: 50px;
        }

        .profile-img {
            max-height: 50px;
            max-width: 50px;
        }

        .account-username {
            font-size: 12pt;
            text-overflow: ellipsis;
        }

        .material-symbols-outlined {
            font-size: 10pt;
        }

        .received-friend-request-text {
            font-size: 8pt;
            word-wrap: break-word;
        }

        .card-right {
            margin: 5px !important;
        }

        .message-button {
            margin: 0 !important;
            padding: 0 !important;
        }

        .send-friend-message-container {
            padding: 0 !important;
            margin-left: 0 !important;
        }

        .message-btn-text {
            font-size: 10pt;
        }

        .container {
            padding-left: 5px;
            padding-right: 5px;
        }
    }

</style>

<div class="container">
    <div class="card mt-5 mb-5">
        {% if friend_list %}
        <div class="d-flex flex-column">
            {% for friend in friend_list %}
            <div class="d-flex flex-row" id="id_account_row">
                <div class="card m-1" id="id_account_card">
                    <div class="d-flex flex-row flex-grow-1 align-items-center">
                        <a class="account-profile-link" href="{% url 'account:profile' pk=friend.id %}">
                            <div class="card-image m-2">
                                <img class="img-fluid profile-img rounded-circle" style="border: 1px solid white; background-color: white;" src="{{ friend.profile_image.url }}" alt="Profile image">
                            </div>
                        </a>
                        <a class="account-profile-link" href="{% url 'account:profile' pk=friend.id %}">
                            <div class="card-body px-2">
                                <h5 class="account-username">
                                    {{ friend.username }}
                                </h5>
                            </div>
                        </a>
                        {% if user == account %}
                        <div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
                            <div class="d-flex flex-row send-friend-message-container justify-content-end p-3">
                                <div class="d-flex flex-row align-items-center btn message-button m-2 px-2" id="id_send_private_message">
                                    <a class="d-flex send-friend-private-message" data-friend-id="{{ friend.id }}" data-request-url="{% url 'privatechat:create_chat' %}"
                                    onclick='sendFriendMessage(this);'>
                                        <span class="d-flex material-symbols-outlined">sms</span>
                                        <span class="d-flex message-btn-text m-auto pl-2">Message</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center">
                <p class="pt-2">
                    No results
                </p>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% include 'chat_scripts/send_message.html' %}

{% endblock content %}

mysite/friends/templates/friends/friend_requests.html
{% extends 'base_menu.html' %}
{% load static %}
{% block content %}

<style type="text/css">

    .card{
        background-color: #303333;
    }

    #id_account_card{
        background-color: #4b4b4d;
        width: 100%;
    }

    .profile-img{
        max-height: 100px;
        max-width: 100px;
    }

    .confirm-or-decline-request-container{
        margin-left: auto;
    }

    #id_account_row{
        width: 100%;
    }

    .card-right{
        width: 100%;
    }

    .account-profile-link {
        text-decoration: none !important;
    }

    .account-username {
        color: white;
        font-size: 20pt;
    }

    .confirm-request-button {
        background-color: #9779a8;
        cursor: pointer;
        transition: background-color 0.2s ease-in-out;
        color: white;
    }

    .confirm-request-button:hover {
        background-color: #b769e0;
        color: white;
    }

    @media (max-width: 649px) {
        .card-image {
            margin: 5px !important;
            max-height: 75px;
            max-width: 50px;
        }

        .profile-img {
            max-height: 50px;
            max-width: 50px;
        }

        .account-username {
            font-size: 12pt;
            text-overflow: ellipsis;
        }

        .material-symbols-outlined {
            font-size: 10pt;
        }

        .received-friend-request-text {
            font-size: 8pt;
            word-wrap: break-word;
        }

        .card-right {
            margin: 5px !important;
        }

        .confirm-friend-request {
            padding: 2px;
            font-size: 7pt;
            margin-right: 0 !important;
        }

        .decline-friend-request {
            padding: 2px;
            font-size: 7pt;
        }

        .container {
            padding-left: 5px;
            padding-right: 5px;
        }
    }

</style>

<div class="container">
    <div class="card mt-5 mb-5">
        {% if friend_requests %}
        <div class="d-flex flex-column">
            {% for friend_request in friend_requests %}
            <div class="d-flex flex-row" id="id_account_row">
                <div class="card m-1" id="id_account_card">
                    <div class="d-flex flex-row flex-grow-1 align-items-center">
                        <a class="account-profile-link" href="{% url 'account:profile' pk=friend_request.sender.id %}">
                            <div class="card-image m-2">
                                <img class="img-fluid profile-img rounded-circle" style="border: 1px solid white; background-color: white;" src="{{ friend_request.sender.profile_image.url }}" alt="Profile image">
                            </div>
                        </a>
                        <a class="account-profile-link" href="{% url 'account:profile' pk=friend_request.sender.id %}">
                            <div class="card-body px-2">
                                <h5 class="account-username">
                                    {{ friend_request.sender.username }}
                                </h5>
                            </div>
                        </a>
                        <div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
                            <div class="d-flex flex-row confirm-or-decline-request-container justify-content-end p-3">
                                <a class="btn confirm-request-button confirm-friend-request mr-1" id="id_confirm_friend_request" data-request-url="{% url 'friends:accept_friend_request' %}" 
                                data-friend-request-id="{{ friend_request.id }}" onclick='acceptFriendRequest(this)'>Confirm</a>
                                <a class="btn btn-secondary decline-friend-request ml-1" id="id_decline_friend_request" data-request-url="{% url 'friends:decline_friend_request' %}" 
                                data-friend-request-id="{{ friend_request.id }}" onclick='declineFriendRequest(this)'>Decline</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center">
                <p class="pt-2">
                    No results
                </p>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}